general {
    hide_cursor         = true
    ignore_empty_input  = true
}

background {
    monitor = DP-2
    path    = screenshot
    blur_passes = 4
    brightness  = 0.5
    zindex  = 1
}

background {
    monitor     =
    path        = screenshot
    blur_passes = 4
    brightness  = 0.5
}

input-field {
    monitor             =
    size                = 200, 50
    check_color         = rgb(30, 107, 204)
    fade_on_empty       = false
    font_color          = rgb(255, 255, 255)
    inner_color         = rgba(0, 0, 0, 0.2)
    outer_color         = rgba(0, 0, 0, 0)
    outline_thickness   = 2
    position            = 0, 0
    rounding            = -1
    valign              = center
}

label {
    monitor     =
    text        = $TIME
    color       = rgba(242, 243, 244, 0.75)
    font_size   = 95
    position    = 0, 200
    halign      = center
    valign      = center
}

label {
    monitor     =
    text        = cmd[update:1000] date +"%a, %d. %b"
    color       =rgba(242, 243, 244, 0.75)
    font_size   = 22
    position    = 0, 100
    halign      = center
    valign      = center
}

label {
    monitor     =
    text        = cmd[update:2000] playerctl metadata --format "\{{ emoji(status) }}  \{{ trunc(title, 30) }} - \{{ artist }}"
    color       = rgba(242, 243, 244, 0.75)
    font_size   = 18
    position    = 0, -100
    halign      = center
    valign      = center
}

label {
    monitor     = 
    text        = cmd[update:2000] (pidof hypridle >/dev/null 2>&1 && echo "ᶻz") || echo ">"
    color       = rgba(242, 243, 244, 0.75)
    font_size   = 36
    position    = 48%, 47%
    halign      = center
    valign      = center
}